from fastapi import FastAPI
from typing import List, Dict, Any
import random

app = FastAPI(
    title="FairMatch API",
    description="Backend API for mock recommendations (Week 2 deliverable).",
    version="1.0",
)

# -------------------------
# Root endpoint (healthcheck)
# -------------------------
@app.get("/")
def root():
    return {
        "status": "ok",
        "message": "FairMatch API is running",
        "version": "1.0",
    }


# -------------------------
# Fake job catalogue (mock data)
# -------------------------
MOCK_JOBS = [
    {
        "job_id": 101,
        "title": "Junior Data Scientist",
        "company": "TechNova",
        "location": "Paris, France",
        "salary_range": "40–50k",
        "skills": ["Python", "Pandas", "Machine Learning"],
    },
    {
        "job_id": 87,
        "title": "Backend Developer",
        "company": "SoftBridge",
        "location": "Lyon, France",
        "salary_range": "38–48k",
        "skills": ["Python", "FastAPI", "PostgreSQL"],
    },
    {
        "job_id": 203,
        "title": "Machine Learning Intern",
        "company": "InnovaLab",
        "location": "Remote",
        "salary_range": "Internship",
        "skills": ["Python", "Scikit-learn", "Git"],
    },
    {
        "job_id": 56,
        "title": "Cloud Engineer (Entry Level)",
        "company": "SkyNetix",
        "location": "Marseille, France",
        "salary_range": "42–52k",
        "skills": ["AWS", "Docker", "Linux"],
    },
    {
        "job_id": 149,
        "title": "AI Research Assistant",
        "company": "DeepVision",
        "location": "Nice, France",
        "salary_range": "45–55k",
        "skills": ["PyTorch", "Deep Learning", "NLP"],
    },
]


# -------------------------
# Recommendation endpoint
# -------------------------
@app.get("/recommend/{user_id}")
def recommend(user_id: int) -> Dict[str, Any]:
    """
    Returns a random mock job recommendation for the given user_id.
    In Week 3 this will be replaced by the real model.
    """

    # choisir 3 jobs aléatoires dans la liste
    recommended_jobs = random.sample(MOCK_JOBS, k=3)

    response = {
        "user_id": user_id,
        "num_recommendations": len(recommended_jobs),
        "recommendations": recommended_jobs,
        "note": "Mock data only. Real recommendations will be generated by the model in Week 3.",
    }
    return response
