from fastapi import FastAPI, UploadFile, Form, File, HTTPException, Depends
from sqlalchemy.orm import Session
from typing import Dict, Any
import random
import fitz  # PyMuPDF

# Import your new DB modules
from lib.gemini_parser import parse_resume_with_gemini
from lib.database import engine, get_db, Base
from lib.models import User

# Create tables automatically (for dev/POC)
Base.metadata.create_all(bind=engine)

app = FastAPI(title="FairMatch API")

app = FastAPI(
    title="FairMatch API",
    description="Backend API",
    version="0.02",
)

# -------------------------
# Root endpoint (healthcheck)
# -------------------------
@app.get("/")
def root():
    return {
        "status": "ok",
        "message": "FairMatch API is running",
        "version": "1.0",
    }


# -------------------------
# Fake job catalogue (mock data)
# -------------------------
MOCK_JOBS = [
    {
        "job_id": 101,
        "title": "Junior Data Scientist",
        "company": "TechNova",
        "location": "Paris, France",
        "salary_range": "40–50k",
        "skills": ["Python", "Pandas", "Machine Learning"],
    },
    {
        "job_id": 87,
        "title": "Backend Developer",
        "company": "SoftBridge",
        "location": "Lyon, France",
        "salary_range": "38–48k",
        "skills": ["Python", "FastAPI", "PostgreSQL"],
    },
    {
        "job_id": 203,
        "title": "Machine Learning Intern",
        "company": "InnovaLab",
        "location": "Remote",
        "salary_range": "Internship",
        "skills": ["Python", "Scikit-learn", "Git"],
    },
    {
        "job_id": 56,
        "title": "Cloud Engineer (Entry Level)",
        "company": "SkyNetix",
        "location": "Marseille, France",
        "salary_range": "42–52k",
        "skills": ["AWS", "Docker", "Linux"],
    },
    {
        "job_id": 149,
        "title": "AI Research Assistant",
        "company": "DeepVision",
        "location": "Nice, France",
        "salary_range": "45–55k",
        "skills": ["PyTorch", "Deep Learning", "NLP"],
    },
]


# -------------------------
# Recommendation endpoint
# -------------------------
@app.get("/recommend/{user_id}")
def recommend(user_id: int) -> Dict[str, Any]:
    """
    Returns a random mock job recommendation for the given user_id.
    In Week 3 this will be replaced by the real model.
    """

    # choisir 3 jobs aléatoires dans la liste
    recommended_jobs = random.sample(MOCK_JOBS, k=3)

    response = {
        "user_id": user_id,
        "num_recommendations": len(recommended_jobs),
        "recommendations": recommended_jobs,
        "note": "Mock data only. Real recommendations will be generated by the model in Week 3.",
    }
    return response


@app.post("/api/parse-resume")
async def parse_resume(
    file: UploadFile = File(...),
    name: str = Form(...),
    gender: str = Form(...),
    interested_domain: str = Form(...),
    db: Session = Depends(get_db)  # Inject Database Session
):
    # 1. Validate File
    if file.content_type != "application/pdf":
        raise HTTPException(status_code=400, detail="File must be a PDF")
    
    # 2. Extract Text
    try:
        pdf_bytes = await file.read()
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        text = "".join([page.get_text() for page in doc])
    except Exception:
        raise HTTPException(status_code=500, detail="Could not read PDF")

    # 3. AI Parsing
    parsed_data = parse_resume_with_gemini(text, interested_domain)
    
    if not parsed_data:
        raise HTTPException(status_code=500, detail="AI parsing failed")

    # 4. Save to PostgreSQL
    new_user = User(
        name=name,
        gender=gender,
        interested_domain=interested_domain,
        age=parsed_data.get("Age"),
        projects=parsed_data.get("Projects"),
        future_career=parsed_data.get("Future_Career"),
        python_level=parsed_data.get("Python_Level"),
        sql_level=parsed_data.get("SQL_Level"),
        java_level=parsed_data.get("Java_Level")
    )
    
    db.add(new_user)
    db.commit()
    db.refresh(new_user)  # Get the generated ID
    
    # 5. Return the saved profile (with ID)
    return {
        "status": "success",
        "user_id": new_user.id,
        "data": parsed_data
    }