from fastapi import FastAPI, UploadFile, Form, File, HTTPException
from typing import List, Dict, Any
import random
from lib.gemini_parser import parse_resume_with_gemini
import fitz  # PyMuPDF

app = FastAPI(
    title="FairMatch API",
    description="Backend API for mock recommendations (Week 2 deliverable).",
    version="1.0",
)

# -------------------------
# Root endpoint (healthcheck)
# -------------------------
@app.get("/")
def root():
    return {
        "status": "ok",
        "message": "FairMatch API is running",
        "version": "1.0",
    }


# -------------------------
# Fake job catalogue (mock data)
# -------------------------
MOCK_JOBS = [
    {
        "job_id": 101,
        "title": "Junior Data Scientist",
        "company": "TechNova",
        "location": "Paris, France",
        "salary_range": "40–50k",
        "skills": ["Python", "Pandas", "Machine Learning"],
    },
    {
        "job_id": 87,
        "title": "Backend Developer",
        "company": "SoftBridge",
        "location": "Lyon, France",
        "salary_range": "38–48k",
        "skills": ["Python", "FastAPI", "PostgreSQL"],
    },
    {
        "job_id": 203,
        "title": "Machine Learning Intern",
        "company": "InnovaLab",
        "location": "Remote",
        "salary_range": "Internship",
        "skills": ["Python", "Scikit-learn", "Git"],
    },
    {
        "job_id": 56,
        "title": "Cloud Engineer (Entry Level)",
        "company": "SkyNetix",
        "location": "Marseille, France",
        "salary_range": "42–52k",
        "skills": ["AWS", "Docker", "Linux"],
    },
    {
        "job_id": 149,
        "title": "AI Research Assistant",
        "company": "DeepVision",
        "location": "Nice, France",
        "salary_range": "45–55k",
        "skills": ["PyTorch", "Deep Learning", "NLP"],
    },
]


# -------------------------
# Recommendation endpoint
# -------------------------
@app.get("/recommend/{user_id}")
def recommend(user_id: int) -> Dict[str, Any]:
    """
    Returns a random mock job recommendation for the given user_id.
    In Week 3 this will be replaced by the real model.
    """

    # choisir 3 jobs aléatoires dans la liste
    recommended_jobs = random.sample(MOCK_JOBS, k=3)

    response = {
        "user_id": user_id,
        "num_recommendations": len(recommended_jobs),
        "recommendations": recommended_jobs,
        "note": "Mock data only. Real recommendations will be generated by the model in Week 3.",
    }
    return response


@app.post("/api/parse-resume")
async def parse_resume(
    file: UploadFile = File(...),
    name: str = Form(...),
    gender: str = Form(...),
    interested_domain: str = Form(...)
):
    # 1. Validate File
    if file.content_type != "application/pdf":
        raise HTTPException(status_code=400, detail="File must be a PDF")
    
    # 2. Extract Text (PyMuPDF)
    try:
        pdf_bytes = await file.read()
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        text = "".join([page.get_text() for page in doc])
    except Exception:
        raise HTTPException(status_code=500, detail="Could not read PDF")

    # 3. AI Parsing
    parsed_data = parse_resume_with_gemini(text, interested_domain)
    
    if not parsed_data:
        raise HTTPException(status_code=500, detail="AI parsing failed")

    # 4. Construct Final Profile
    full_profile = {
        "Name": name,
        "Gender": gender,
        "Interested_Domain": interested_domain,
        # Spread the parsed data fields
        **parsed_data 
    }
    
    return full_profile